### ISSUE TITLE
reason to limit variable names?

### ISSUE THREAD

**Issue by Nom-DePlume** [codeplea/tinyexpr#20]
Is there a compelling reason that variable names are limited to starting with a-z?

I needed $ to be a variable to process some data but that opens the question of what others may need.  

trivial change, 2 lines in next_token I can do a pull request if need be I just did not know if there was a good reason to limit it.

**Comment by EvilPudding** [comment]
Don't think there is, completely agree, `$` and `_` should be allowed as they are in standard C.

**Comment by codeplea** [comment]
Thanks for the feedback.

> trivial change, 2 lines in next_token

It's a trivial change because the code is kept simple. If I add in more features, then changes like this become harder. What if we allow `$` to be a variable, but then someone else wants to modify TinyExpr to use `$` as an operator (maybe to represent finical operations of some sort)? If `$` was officially allowed in variable names, what would the rules be exactly? Are variables allowed to start with `$`? Can it appear in the middle of a variable? Is `$` all by itself a valid variable name?

I think it makes more sense for you to modify TinyExpr as you see fit for your project, and others to do the same. TinyExpr being kept simple facilitates this.

> $ and _ should be allowed as they are in standard C.

I really don't think `$` is allowed in standard C.

**Comment by Nom-DePlume** [comment]
fair enough, thats why I asked.  

$ is not allowed under the standard

http://www.c4learn.com/c-programming/c-variable-nameing-rules/

**Comment by EvilPudding** [comment]
Looks like I was wrong, many implementations allow it though.
