### ISSUE TITLE
Implicit multiplication?

### ISSUE THREAD

**Issue by PascalKoe** [codeplea/tinyexpr#37]
Thanks for your effort in this project.
I have been wondering if there is a way to evaluate terms with implicit multiplication.

```
2x
2sin(x)
sin(x)cos(x)
2(5)
...
```
Is that to much weight for **Tiny**Expr?

Thanks in advance

**Comment by codeplea** [comment]
>I have been wondering if there is a way to evaluate terms with implicit multiplication.

It's not a current feature, but you should be able to do that with only changing a line or two. Look here: https://github.com/codeplea/tinyexpr/blob/master/tinyexpr.c#L476 Give it a try and let me know how it turns out.

>Is that to much weight for **Tiny**Expr?

Haha. No, you have it backwards. Being tiny keeps things simple and makes it *easier* to change.

**Comment by nicolasdanet** [comment]
IMHO, it might be impossible in that case to parse without ambiguity.

`2acos(b) can be 2*a*cos(b) or 2*acos(b)`

There's a ton of examples like this that quickly leads to hell.

**Comment by EvilPudding** [comment]
Why not leave spaces between what you want to multiply? `2sin(x)` is illegible.
