### ISSUE TITLE
Out of memory check and static memory implementation

### ISSUE THREAD

**Issue by stawiski** [codeplea/tinyexpr#56]
Hey guys,

I've used the library for a while in an embedded environment and noticed two things:
- You don't support the case of failed memory allocation, which can happen in resource-constrained devices.
In `new_expr(...)`:
```
    te_expr *ret = malloc(size);
    memset(ret, 0, size);
```
 - It would be nice to have the option of static memory allocation for embedded applications. That is to drop `malloc()` whatsoever as a preprocessor configuration option, and preallocate the memory in a configurable size given by the user. That would limit of course the amount of parseable nested expressions to the given configured size.

Are you interested in implementing that or me dropping in some PRs?

Cheers

**Comment by RallyTronics** [comment]
I would find that very useful, I have looking at tinyexpr for an embedded application.

**Comment by stawiski** [comment]
I ended up implementing it myself ;)

Got the static memory working, now I'm finishing up propagating the error when new expression memory allocation fails.

Also run into even more compilation issues, this time with IAR C compiler, it's aggressive when it comes to casting types without explicit cast.

**Comment by RallyTronics** [comment]
Looks like you are making good progress!  I use IAR as well.

**Comment by stawiski** [comment]
I finished it, but as you can see, the dev is not responding.

**Comment by codeplea** [comment]
If you want to share your code, I'll take a look.

I'm hesitant to support this, though. I'm sure it's useful. I don't doubt that.

Here's my concern. tinyexpr's biggest feature is that it's not a lot of code. It's tiny. If someone doesn't like `malloc()`, they can just hack tinyexpr up so it doesn't use it. It's easy because it's short. Every time we add a feature, it makes it that much less hack-able, regardless of how useful that new feature is.

**Comment by codeplea** [comment]
>Also run into even more compilation issues, this time with IAR C compiler, it's aggressive when it comes to casting types without explicit cast.

I'm sympathetic. I've worked with several bad embedded C compilers over my carrier. It's really weird that IAR C won't let you implicit cast from `void*`. That is a major feature of C since `void*` was introduced for this reason. Making the cast explicit just feels weird. Like a bad C++ anti-pattern.

**Comment by stawiski** [comment]
@codeplea I see, that's cool.
I created a PR that implements static memory as an option, propagates memory allocation failure, and fixes compiler warnings for IAR and MVSC. If you have some time please review it.

I also have unit tests in Catch2 for this - it's basically a port of your unit tests plus cases of failed memory allocation.

Cheers
