### ISSUE TITLE
Invalid parsing "2++-3" expression

### ISSUE THREAD

**Issue by jherkel** [codeplea/tinyexpr#6]
There is a problem with these types of expressions. For example 2++-3  returns -1 but I think it is not valid expression.

**Comment by codeplea** [comment]
I consider `2++-3` to be a valid expression. It's valid in almost all programming languages.

For example, try this C code:
```C
#include <stdio.h>

int main(void) {
	printf("%f", 2 + + -3); /* Spaces added because C has a ++ operator */
	return 0;
}
```

It is also valid in Excel spreadsheets without modification. Also the Tcl programming language. With a space added, it's a valid expression in PHP, Python, Ruby, Perl, Java, Javascript, and probably most others.

In fact, the only language I tested that didn't like it was Lua.

Why do you think it's invalid?

**Comment by codeplea** [comment]
They way the algebra works here is that `5` and `+5` are the same number. The `+` isn't needed, because it is assumed, but it is allowed. If we generalize that to `x` and `+x` being exactly the same, then you could imagine putting `+5` in `x`. In that case, `+x` will expand out to `++5`, which is still just exactly `5`.
