### ISSUE TITLE
Usage with different types

### ISSUE THREAD

**Issue by pedro-ricardo** [codeplea/tinyexpr#93]
Hello there, thanks for the cool library you got here.

Let's say that I want to use this library but not with real or double types, but a type that I've created .. obviously this type is implemented to support basic operations.
My goal is to evaluate an expression made with custom a custom type, and have the answer as the same type.

How traumatic is the change I need to do to achieve this ?

**Comment by codeplea** [comment]
A primary design goal of TinyExpr was to be able to easily allow changes like this. That's why the code is kept small and short. Just open `tinyexpr.c` and search for `double`. You'll need to change those to your type, and also you'll want to disable the built-in functions which only operate on double.
